// Language aliases supported by CodeMirror
// https://github.com/codemirror/language-data/blob/main/src/language-data.ts

export const languagesAliases = {
  cpp: 'c++',
  cassandra: 'cql',
  xhtml: 'html',
  ecmascript: 'javascript',
  js: 'javascript',
  node: 'javascript',
  json5: 'json',
  ts: 'typescript',
  rss: 'xml',
  wsdl: 'xml',
  xsd: 'xml',
  yml: 'yaml',
  asciiarmor: 'pgp',
  csharp: 'c#',
  cs: 'c#',
  coffee: 'coffeescript',
  'coffee-script': 'coffeescript',
  lisp: 'common lisp',
  fsharp: 'f#',
  jsonld: 'json-ld',
  ls: 'livescript',
  'objective-c': 'objective-c',
  objc: 'objective-c',
  'objective-c++': 'objective-c++',
  'objc++': 'objective-c++',
  ini: 'properties files',
  properties: 'properties files',
  rscript: 'r',
  jruby: 'ruby',
  macruby: 'ruby',
  rake: 'ruby',
  rb: 'ruby',
  rbx: 'ruby',
  bash: 'shell',
  sh: 'shell',
  zsh: 'shell',
  sparul: 'sparql',
  excel: 'spreadsheet',
  formula: 'spreadsheet',
  tex: 'latex',
};

export type LanguageAlias = keyof typeof languagesAliases;
